language: node_js
node_js:
- '10'
cache:
  "-directories":
    - node_modules

install:
  - npm install

before_script:
  - openssl aes-256-cbc -K $encrypted_be6814600c10_key -iv $encrypted_be6814600c10_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp ssh_config ~/.ssh/config
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"
  - npm run build:dll

script:
  - npm run build

deploy:
  type: git
  repository: https://github.com/liweidee/liwei.github.io.git
  branch: master

after_script:
  - cd ../
  - git clone https://github.com/liweidee/liwei.github.io.git
  - cp -R ./react_cli_multi/dist/ ./liwei.github.io/
  - cd ./liwei.github.io/
  - git add .
  - git commit -m "CI Update"
  - git pull
  - git push --force origin master
  - cd ../
  - rm -rf ./liwei.github.io

branches:
  only:
    - develop

env:
  global: 


