language: node_js
# nodejs版本
node_js:
  - '10'

# Travis-CI Caching
cache:
  -directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:
  - npm run build:dll

# 发布构建
script:
  - npm run build

after_script:
  #- cd ./dist
  #- git init
  #- git remote add origin https://github.com/liweidee/liwei.github.io.git
  #- git config user.name "${U_NAME}"
  #- git config user.email "${U_EMAIL}"
  #- git add .
  #- git commit -m "Update CI"
  #- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}

  - cd ../
  - git clone https://github.com/liweidee/liwei.github.io.git
  - cp -R ./react_cli_multi/dist/ ./liwei.github.io/
  - cd ./liwei.github.io/
  - git add .
  - git commit -m "CI Update"
  - git remote rm origin
  - git remote add origin https://1642745510@qq.com:1642745510@qq.com@github.com/liweidee/liwei.github.io.git
  - git push origin master
  - cd ../
  - rm -rf ./liwei.github.io
# E: Build Lifecycle

# 指定分支
branches:
  only:
    - develop

env:
  global:
    