language: node_js
node_js:
- '10'
cache:
  "-directories":
  - node_modules

env:
  global:
    - U_NAME: liwei

install:
- npm install

before_script:
  - openssl aes-256-cbc -K $encrypted_be6814600c10_key -iv $encrypted_be6814600c10_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 47.240.11.137\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ls ~/.ssh/
  - cat ~/.ssh/config
  - npm run build:dll

addons:
  ssh_known_hosts: 47.240.11.137

script:
- npm run build

after_success:
  - pwd
  - scp -o StrictHostKeyChecking=no -r ./dist/ root@39.107.226.67:/home/ftpuser/
  # - rsync --version
  # - rsync -o 'stricthostkeychecking=no' -r ./dist/ root@39.107.226.67:/home/ftpuser/
  # - cat /etc/ssh/sshd_config
  # - rsync --version
  # - rsync -av ./dist/ root@39.107.226.67:/home/ftpuser/

after_script:
  #- ls ./dist/
  #- git clone https://${GH_REF} gh_web_git
  #- cd gh_web_git
  #- git checkout master
  #- cp -R ../react_cli_multi/dist/ ./gh_web_git/
  #- git config user.name "${U_NAME}"
  #- git config user.email "${U_EMAIL}"
  #- git add .
  #- git commit -m "CI Update"
  #- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
  #- cd ../
  #- rm -rf ./liwei.github.io

branches:
  only:
    - develop
