language: node_js
# nodejs版本
node_js:
  - '10'

# Travis-CI Caching
cache:
  -directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:
  - MIIEowIBAAKCAQEAl2yXx68k2kLwVFnWn3/Js/GdR/pettymUxvTG4nIU53YBt3y
nrt4QGDms65/N0Sp7rDDsw1Ize6N+fEzPY9B+y+GjRMxTGtFrCEBVD5ddx4JU0ZC
FPRAAdOWcUGgDIKBOPX96CjJaW69qvZ4hVtHuGEfZtLJXZcjXmwwMra+uonAI9fI
U7b2r1mEtrtqzJeeb3q9w6P81W6aWsowE1TCxmw9VUjYcetodQXJGMuoMM+ijOCv
vvL/Tf0aalUVqpCOeNXpQpg2veHhzeorPTBDdxiuiNuFzj0j/W05FyS0rRxre5bf
KwfdQitqpiqKrGZ6sFSax4wFoFMb+PCGn6l4+wIDAQABAoIBAANgK14LPIIVHfBz
dEJoAeIeD8iL/1KKRrbxlto1Tx72FNvKVN9PBJZC0sHMsQ9VW4hzrlkugaH9oHKi
+uZzbCAiZhh9BgtTFOGKdtIe9cxzAfg2R8DZ1Rd1VRQ/R0cgHatcaIWlayALlPTb
u8IVT9r/Z0jOiCiq9uHi/YwT4NqdsMB/TTDoZOo2bShVqioYWcGytkiU0Hj9s2/e
dDaFLK2QOqOBK/jyiZf8mcYkpOF4A+WTALlx4UBauKyB8EV2+vWXepOlMDQkCP5y
7ExgThEJR7cSbW4t8sDyiM7p6XIhi3anJ2iaaaZ3yhfFIRGl/KLSvuiI7hvCcgvE
nxEBQMECgYEAxohyE4dJof4nhp5I0PmFfXC3mKoHaf6ppQf5UQT18fw8e0J3Jnoj
VmV1L2Hj1EDS9VVmZ8aJUMECP5ZBOr9oEiXqVD04FftNSQyQ8ZHWGiBRjgiAl+I3
4DHMlSG9SBpB7yHGNH5wVmOcx0AmazkMn+5I9zpSevU2KwVjz/fYumECgYEAw0FS
1jq29JBebyfl/CqXf8gvnGAIrSgKzAvesxRvbU8yWdziQfrYnzLAIK4/FaBHbrv2
owHxtSsJCvl3xUupYANK36TefWUlIbHErlCoDtIS3drrkznAw7nhKkaUvmUfPnZx
gpc+/r4QYT3Z7CY+S3WU4pUjWdXyC7kVan/PCNsCgYBjGGgYZ0bRnNKN1yPxaxq+
aiy5/uSEe6Chx0Eit58rkgN+YsamZgCNd0bux6W4pEKoQmBDHE4eCLjelFkqwa9o
n5Q/R+9eyXjiJWuTqH99uvP6OTQ2m6vYNAMxzQ11l+WhPvJ38USRWlc+/T4v9uHe
UkoJXQseZJcNEjun6sY7AQKBgHkIFQEWhDI1C1R7tuQIwsBCpsCYBsjO+WJiOTlo
gWmQnfV2JgogJAcKvm2DlTcikyTg/pEss1dJxeE3ojZ6IBOT9uWKnR+9grbQKsqi
1InbTjaXbU9ljUfGAPzjo3Ah3qwpX1NDzZi62Axu+paXXiYITLHnIHKfW9pIcC4D
66HhAoGBALbAkxG299X4OkHjN4uQH2l26l1BrszamPZGVfPuze9I67p95+YSE84U
IVhzNPswjyD1FaUyqb9Sk3ou5r6g9CNv5Lu0ILUF+eveXkC2782t8eb1z10FvTeN
8TDQ2b5b+2Mp+fl1qqvP4N4LMy0RThn+naDa8S8CrZBaMrrzqjLK
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - cp .travis/ssh_config ~/.ssh/config
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - npm run build:dll

# 发布构建
script:
  - npm run build

after_script:
  #- cd ./dist
  #- git init
  #- git remote add origin https://github.com/liweidee/liwei.github.io.git
  #- git config user.name "${U_NAME}"
  #- git config user.email "${U_EMAIL}"
  #- git add .
  #- git commit -m "Update CI"
  #- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}

  - cd ../
  - git clone https://github.com/liweidee/liwei.github.io.git
  - cp -R ./react_cli_multi/dist/ ./liwei.github.io/
  - cd ./liwei.github.io/
  - git add .
  - git commit -m "CI Update"
  - git push origin master
  - cd ../
  - rm -rf ./liwei.github.io
# E: Build Lifecycle

# 指定分支
branches:
  only:
    - develop

env:
  global:
    